/**
 * server.json is the registry's copy of everything this repository claims about
 * itself, and it is the one public artefact no other test reads.
 *
 * Two failure modes, both silent:
 *
 * 1. THE SIZE CAP. The MCP registry accepts at most 4096 bytes of
 *    publisher-provided `_meta`. Over that, publication is refused — and nothing
 *    in the build says so, because the file is still valid JSON and still parses.
 *    The prose in here is the kind that grows a sentence at a time, so the cap is
 *    asserted rather than remembered.
 *
 * 2. DISAGREEMENT WITH THE README. Both files ship a paste-ready client config.
 *    A reader meets one or the other, not both, so if they select different
 *    environments then half the readers land somewhere they did not choose — and
 *    the default is production, which is the half that costs money.
 *
 * Offline, and reads only tracked files.
 */

import { describe, it, expect } from "@jest/globals";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import {
  TOOL_ANNOTATIONS,
  TastytradeMCPServer,
} from "../src/mcp-server/index.js";
import { accessClassFor } from "../src/mcp-server/annotations.js";
import { apiEnvironmentOf, resolveApiUrl } from "../src/mcp-server/index.js";
import { REQUIRED_DOCS } from "../src/resources/static/vendored-docs.js";

const REPO_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);

function read(name: string): string {
  return readFileSync(path.join(REPO_ROOT, name), "utf8");
}

const MANIFEST = JSON.parse(read("server.json")) as Record<string, unknown>;
const PUBLISHER_KEY = "io.modelcontextprotocol.registry/publisher-provided";

/** The registry's documented ceiling on publisher-provided `_meta`. */
const META_BYTE_CAP = 4096;

interface Published {
  toolSurface?: {
    tools?: number;
    readOnly?: number;
    write?: number;
    destructive?: number;
  };
  install?: {
    cloneAndBuild?: {
      clientConfig?: {
        mcpServers?: Record<string, { env?: Record<string, string> }>;
      };
    };
  };
}

function published(): Published {
  const meta = MANIFEST._meta as Record<string, unknown>;
  return meta[PUBLISHER_KEY] as Published;
}

/**
 * The compliance notice is supplied by tastytrade compliance and reproduced
 * verbatim in README.md. It is held here as a literal so that reformatting,
 * abridging, or "tidying" it fails the build rather than shipping quietly — the
 * wording is not ours to adjust, and a prettier reflow or a well-meant edit is
 * exactly how mandated language drifts.
 *
 * Compared with whitespace collapsed, because markdown line wrapping is allowed
 * to change and the words are not.
 */
const COMPLIANCE_NOTICE =
  "tastytrade does not endorse or recommend any third-party AI System connected " +
  "via the MCP server, and tastytrade is not responsible for any information, " +
  "output, or trading activity generated by or through your connected AI System. " +
  "You are solely responsible for any actions taken in reliance on information " +
  "generated by your AI System and for any investment or trading decisions made " +
  "using it. tastytrade does not guarantee the accuracy, completeness, or " +
  "suitability of any of your AI generated output.";

describe("the compliance notice is present and unaltered", () => {
  const readme = read("README.md");

  /** README prose with wrapping collapsed, comments stripped. */
  function flattened(): string {
    return readme
      .replace(/<!--[\s\S]*?-->/g, "")
      .split(/\s+/)
      .join(" ");
  }

  it("appears in README.md word for word", () => {
    expect(flattened()).toContain(COMPLIANCE_NOTICE);
  });

  it("sits under its own heading, so it reads as a notice rather than as our prose", () => {
    expect(readme).toMatch(/^## Notice$/m);
    const idx = readme.indexOf("## Notice");
    const licence = readme.indexOf("## Licence");
    // Last section: nothing but the notice may follow it.
    expect(idx).toBeGreaterThan(licence);
  });

  it("carries the do-not-reword marker for whoever edits next", () => {
    const idx = readme.indexOf("## Notice");
    const section = readme.slice(idx, idx + 600);
    expect(section).toMatch(/verbatim/i);
    expect(section).toMatch(/[Dd]o not reword/);
  });

  it("is reachable from the top of the file and from the disclaimer", () => {
    // A notice a reader never arrives at is decoration.
    expect(readme).toContain("[Notice](#notice)");
    expect(
      (readme.match(/\[Notice\]\(#notice\)/g) ?? []).length,
    ).toBeGreaterThanOrEqual(2);
  });
});

describe("server.json fits what the registry will accept", () => {
  it("keeps _meta under the 4096-byte publisher-provided cap", () => {
    // Serialised the way a publisher sends it — no pretty-printing, since the
    // cap is on the payload and not on the file as it sits on disk.
    const bytes = Buffer.byteLength(JSON.stringify(MANIFEST._meta), "utf8");
    expect(bytes).toBeLessThanOrEqual(META_BYTE_CAP);
  });

  it("is not vacuously small — the cap is a real bound on this file", () => {
    // Without this, deleting _meta entirely would satisfy the test above.
    const bytes = Buffer.byteLength(JSON.stringify(MANIFEST._meta), "utf8");
    expect(bytes).toBeGreaterThan(META_BYTE_CAP / 2);
  });

  it("declares the version package.json declares", () => {
    const pkg = JSON.parse(read("package.json")) as { version: string };
    expect(MANIFEST.version).toBe(pkg.version);
  });
});

describe("server.json agrees with the code it describes", () => {
  it("advertises the tool counts the registry actually serves", () => {
    const server = Object.create(
      TastytradeMCPServer.prototype,
    ) as TastytradeMCPServer;
    const tools = (
      TastytradeMCPServer.prototype as unknown as {
        getTools: (this: TastytradeMCPServer) => Array<{ name: string }>;
      }
    ).getTools.call(server);

    const counts = { read: 0, write: 0, destructive: 0 };
    for (const t of tools) {
      const annotations = TOOL_ANNOTATIONS[t.name];
      expect(annotations).toBeDefined();
      counts[accessClassFor(annotations!)] += 1;
    }

    const surface = published().toolSurface ?? {};
    expect(surface.tools).toBe(tools.length);
    // Only assert the breakdown the file actually publishes, so adding a field
    // here is a deliberate act rather than something this test demands.
    if (surface.readOnly !== undefined)
      expect(surface.readOnly).toBe(counts.read);
    if (surface.write !== undefined) expect(surface.write).toBe(counts.write);
    if (surface.destructive !== undefined)
      expect(surface.destructive).toBe(counts.destructive);
  });
});

describe("the licence story covers what the server needs to run", () => {
  /**
   * The software is MIT; the vendored tastytrade documentation is not. Four of
   * those files are read at module load, so a recipient who received only the
   * MIT grant could fork this repository and still not lawfully ship anything
   * that starts. NOTICE is what closes that, which makes it load-bearing rather
   * than decorative — so it is asserted rather than reviewed.
   */
  const notice = read("NOTICE");

  it("ships a NOTICE that names every doc the server requires at runtime", () => {
    for (const file of REQUIRED_DOCS) {
      expect(notice).toContain(file);
    }
  });

  it("grants redistribution of the vendored docs, and says it is not MIT", () => {
    expect(notice).toMatch(/redistribute/i);
    expect(notice).toMatch(/does NOT place it under the MIT License/);
    // The grant has to survive being copied, or a fork's fork is unlicensed.
    expect(notice).toMatch(/retained with the copy/i);
  });

  it("is pointed to from LICENSE, README and server.json", () => {
    // A reader who opens only one of them must not conclude everything is MIT.
    expect(read("LICENSE")).toContain("NOTICE");
    expect(read("README.md")).toContain("[NOTICE](NOTICE)");
    expect(JSON.stringify(published())).toContain("NOTICE");
  });

  it("no longer claims the vendored docs carry no licence of their own", () => {
    // The exact sentence this replaced. A revert would put the hole back
    // silently, since nothing about it breaks a build.
    expect(read("README.md")).not.toMatch(
      /carries no licence notice of its own/,
    );
  });
});

describe("the two paste-ready configs cannot disagree", () => {
  /** The env block server.json tells a reader to paste. */
  function manifestEnv(): Record<string, string> {
    const servers =
      published().install?.cloneAndBuild?.clientConfig?.mcpServers;
    expect(servers).toBeDefined();
    const entry = Object.values(servers!)[0];
    expect(entry?.env).toBeDefined();
    return entry!.env!;
  }

  /** Every `TASTYTRADE_ENV` value appearing in a README json fence. */
  function readmeEnvValues(): string[] {
    const readme = read("README.md");
    const values: string[] = [];
    for (const fence of readme.matchAll(/```json\n([\s\S]*?)```/g)) {
      for (const m of fence[1].matchAll(/"TASTYTRADE_ENV"\s*:\s*"([^"]+)"/g)) {
        values.push(m[1]);
      }
    }
    return values;
  }

  it("names an environment explicitly in server.json", () => {
    // An absent variable means production. A config that means production
    // without saying so is how an operator reaches it without deciding to, so
    // the block has to name it either way.
    expect(manifestEnv().TASTYTRADE_ENV).toBeDefined();
  });

  it("names an environment explicitly in the README's config block", () => {
    expect(readmeEnvValues().length).toBeGreaterThan(0);
  });

  /** The uncommented TASTYTRADE_ENV assignment in .env.sample, if any. */
  function envSampleValue(): string | undefined {
    for (const line of read(".env.sample").split("\n")) {
      const m = /^TASTYTRADE_ENV=(.*)$/.exec(line.trim());
      if (m) return m[1].trim();
    }
    return undefined;
  }

  it("selects the SAME environment in all THREE paste-ready artifacts", () => {
    // README.md, server.json and .env.sample are each a block somebody copies.
    // A reader meets ONE of them, so if they disagree, some fraction of users
    // land in an environment the documentation did not promise — and on this
    // server the two environments differ by whether orders spend real money.
    //
    // This test previously compared only the first two. .env.sample shipped
    // `TASTYTRADE_ENV=sandbox` while both others named production, and an agent
    // that copied the sample reported the server had "defaulted to sandbox" —
    // correctly, for the file it had been handed.
    const fromManifest = manifestEnv().TASTYTRADE_ENV;
    for (const value of readmeEnvValues()) {
      expect(value).toBe(fromManifest);
    }
    expect(envSampleValue()).toBe(fromManifest);
  });

  it("does not let .env.sample contradict the resolver's own default", () => {
    // Stronger than agreement between documents: what the sample names must be
    // what an unconfigured server actually does. Read from the resolver rather
    // than restated, so this cannot drift if the default moves again.
    const sample = envSampleValue();
    expect(sample).toBeDefined();
    expect(apiEnvironmentOf(resolveApiUrl({}))).toBe(sample);
  });

  it("selects an environment the server can actually read", () => {
    // A paste-ready block naming an unreadable environment would fail closed to
    // the sandbox — safe, but not what either file says it does.
    const value = manifestEnv().TASTYTRADE_ENV;
    expect([
      "production",
      "prod",
      "live",
      "sandbox",
      "cert",
      "staging",
      "sbx",
    ]).toContain(value);
  });
});
